services:
  taskmanager-backend:
    image: 'taskmanager:latest'
    build:
      context: ./backend
    container_name: taskmanager-backend
    depends_on:
      taskmanager-postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskmanager-postgres:5432/taskmanager-postgres
      - SPRING_DATASOURCE_USERNAME=taskmanager-postgres
      - SPRING_DATASOURCE_PASSWORD=taskmanager-postgres-pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - 8080:8080

  taskmanager-frontend:
    image: 'taskmanager-frontend:latest'
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: taskmanager-frontend
    depends_on:
      - taskmanager-backend
    ports:
      - 80:80

  taskmanager-postgres:
    image: 'postgres:13.1-alpine'
    container_name: taskmanager-postgres
    environment:
      - POSTGRES_USER=taskmanager-postgres
      - POSTGRES_PASSWORD=taskmanager-postgres-pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanager-postgres -d taskmanager-postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5432:5432
